version: "3.8"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    ports:
      - "3001:3001"
    volumes:
      - uptime-kuma-data:/app/data
    restart: unless-stopped
    networks:
      - kuma-network

  kuma-sentinel:
    build: .
    container_name: kuma-sentinel
    environment:
      - KUMA_URL=http://uptime-kuma:3001
      - KUMA_USER=admin
      - KUMA_PASS=changeme
      - SENTINEL_NAME=INTERNET-SENTINEL
      - TAG_TO_SUPPRESS=internet-dependent
    depends_on:
      - uptime-kuma
    restart: unless-stopped
    networks:
      - kuma-network

volumes:
  uptime-kuma-data:

networks:
  kuma-network:
    driver: bridge
