name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Release Notes
        id: notes
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          PREV_TAG=$(git describe --tags --abbrev=0 $TAG^ 2>/dev/null || echo "")

          if [ -z "$PREV_TAG" ]; then
            echo "First release, getting all commits..."
            COMMITS=$(git log --pretty=format:"- %s (%an)" --reverse)
          else
            echo "Getting commits since $PREV_TAG..."
            COMMITS=$(git log $PREV_TAG..$TAG --pretty=format:"- %s (%an)")
          fi

          # Write to file to preserve newlines
          cat << EOF > release_notes.md
          ## What's Changed

          $COMMITS

          ## Docker Image

          \`\`\`bash
          docker pull ghcr.io/${{ github.repository }}:$TAG
          \`\`\`

          ---
          *Full Changelog*: ${PREV_TAG:+https://github.com/${{ github.repository }}/compare/$PREV_TAG...$TAG}
          EOF

          echo "Generated release notes"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: release_notes.md
          draft: false
          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-beta') || contains(github.ref, '-alpha') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}